Install java dependencies with the custom build.gradle script instead of apt-get
CodeSignal/dockerfiles pull request #221
Opened 2020-11-26 20:30 UTC by roma0297

https://github.com/CodeSignal/coderunner/issues/882

2020-11-26 21:29 UTC, DimaPhil approved these changes

2020-11-27 06:09 UTC, Albinutte requested changes
Let's do some testing before merging this this time 😄 I pulled this image on a coderunner, and updated coderunner to target it. However, this code snippet still doesn't run for me:
```java
import java.io.*;

// Main class should be named 'Solution'
class Solution {
    public static void main(String[] args) {
        com.fasterxml.jackson.dataformat.csv.CsvSchema().builder();
    }
}
```

I get compilation error as a verdict, and
```
"/usercode/FILESYSTEM/main.java:6: error: package com.fasterxml.jackson.dataformat does not exist
        com.fasterxml.jackson.dataformat.csv.CsvSchema().builder();
                                        ^
1 error
"
```

in the logs. How do I make sure that it's working correctly?

2020-11-27 21:33 UTC, roma0297 commented
> Let's do some testing before merging this this time 😄 I pulled this image on a coderunner, and updated coderunner to target it. However, this code snippet still doesn't run for me:
> 
> ```java
> import java.io.*;
> 
> // Main class should be named 'Solution'
> class Solution {
>     public static void main(String[] args) {
>         com.fasterxml.jackson.dataformat.csv.CsvSchema().builder();
>     }
> }
> ```
> 
> I get compilation error as a verdict, and
> 
> ```
> "/usercode/FILESYSTEM/main.java:6: error: package com.fasterxml.jackson.dataformat does not exist
>         com.fasterxml.jackson.dataformat.csv.CsvSchema().builder();
>                                         ^
> 1 error
> "
> ```
> 
> in the logs. How do I make sure that it's working correctly?

Hi Albina! I was checking using the following code:
```
import java.io.*;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

// Main class should be named 'Solution'
class Solution {
    public static void main(String[] args) {
        YAMLFactory factory = null;
        System.out.println("Hello, World");
    }
}
```

2020-11-29 09:21 UTC, Albinutte approved these changes
Noice! It does work then 😄

2020-11-29 12:15 UTC, merged