Python Ubuntu 20.04
CodeSignal/dockerfiles pull request #282
Opened 2021-02-03 14:28 UTC by ArDrambyan

Closes #264 #265 

## Changes
Updated `Python2` and `Python3` images to be based on `Ubuntu 20.04`

2021-02-03 20:47 UTC, ArDrambyan commented
@menewman - I don't have any fully tested coderunner for now, but I deployed coderunners 68.183.28.148 and 142.93.58.135 with these changes, so the tests should be finished soon

2021-02-03 21:22 UTC, menewman requested changes
Although the tests are not done, it looks like there may be an issue with Python 3 raw tests! Template tests are still going, so I'm not sure about those ones.

![Screen Shot 2021-02-03 at 1 20 08 PM](https://user-images.githubusercontent.com/747378/106811189-d4cc1d80-6622-11eb-8eaa-5470657a0643.png)

2021-02-03 21:22 UTC, menewman commented on python2/Dockerfile
> +RUN wget --quiet https://raw.githubusercontent.com/paulfitz/mysql-connector-c/master/include/my_config.h -P /usr/include/mysql/
Reliance on the `master` branch of someone's GitHub repo that we don't have control over makes me a little nervous. Why do we need this for the new Ubuntu version when we didn't before?

2021-02-04 07:04 UTC, ArDrambyan commented on python2/Dockerfile
> +RUN wget --quiet https://raw.githubusercontent.com/paulfitz/mysql-connector-c/master/include/my_config.h -P /usr/include/mysql/
I was getting `my_config.h` missing error for `MySql-Python` package installation. I was trying to fix it by installing some package instead of copying that file but I couldn't find any package that will fix this issue. I Will look into it one more time

2021-02-04 10:20 UTC, ArDrambyan commented on python2/Dockerfile
> +RUN wget --quiet https://raw.githubusercontent.com/paulfitz/mysql-connector-c/master/include/my_config.h -P /usr/include/mysql/
I downloaded `my_config.h` from https://dev.mysql.com/doc/dev/mysql-server/8.0.11/my__config_8h_source.html to remove any dependency

2021-02-04 15:10 UTC, ArDrambyan commented
@menewman - finally coderunner 157.230.212.197 with latest changes passes the tests

2021-02-05 19:53 UTC, menewman approved these changes
Thanks for the changes, Aram! I am still a little worried about the config file (I think it must be masking another issue, right?) but willing to approve -- my concern about depending on an unreliable dependency is resolved by at least copying the file into this repo 👍

2021-02-08 07:33 UTC, ArDrambyan commented
> I am still a little worried about the config file (I think it must be masking another issue, right?)

I did a lot of search for it and looks like it's not a rare issue and the main solution in all answers was something like - "make sure that my_config.h file exists in /usr/lib/mysql directory" and I don't know why we didn't face this issue on the ubuntu 16.04

2021-02-08 07:33 UTC, merged