Ubuntu version 20.04
CodeSignal/dockerfiles pull request #325
Opened 2021-03-17 10:00 UTC by ArDrambyan

Closes #324 

## Changes

Resolved conflicts with the master branch

2021-03-18 02:48 UTC, menewman approved these changes
Phew, what a big merge! Nice to see it all coming together. Approving this overall since the images should all be working individually, but with one small comment about the CircleCI/Git change detection.

2021-03-18 02:48 UTC, menewman commented on .circleci/config.yml
> +            FILES=$(git diff-tree --name-only -r --diff-filter=ACMRT origin/276-ubuntu-version-20 HEAD)
Should we change this back to `origin/master` before merging?

2021-03-18 09:30 UTC, ArDrambyan commented on .circleci/config.yml
> +            FILES=$(git diff-tree --name-only -r --diff-filter=ACMRT origin/276-ubuntu-version-20 HEAD)
yeah, I forgot to revert it, thanks!

2021-03-18 11:45 UTC, ArDrambyan commented
@menewman - CI is failing because it tries to rebuild everything :D

2021-03-18 16:04 UTC, menewman commented
@ArDrambyan - If it's just a one time failure due to the way we calculate changed files in CircleCI, I think the answer is probably a GitHub admin override, which I'm happy to help with. But also, the other thing we should do is release these base updates in layers? First, base. Then, update the Dockerfiles to all inherit from base v9.0, then the next layer of dependencies?

2021-03-19 05:01 UTC, ArDrambyan commented
> If it's just a one time failure due to the way we calculate changed files in CircleCI, I think the answer is probably a GitHub admin override, which I'm happy to help with

It would be great!





> But also, the other thing we should do is release these base updates in layers? First, base. Then, update the Dockerfiles to all inherit from base v9.0, then the next layer of dependencies?

I think yes, maybe I'll create intermediate branches to test dockerfiles chunk by chunk but the main idea is to do deploy them layers by layers

2021-03-19 22:24 UTC, menewman requested changes
Based on our conversation in Slack, I'm setting status to "request changes" to await the strategy of splitting into small PRs that we can merge and release, layer by layer

2021-03-26 14:16 UTC, closed without merging