Make sure that kotlin-scripting-compiler-embeddable is loaded during …
CodeSignal/dockerfiles pull request #340
Opened 2021-03-24 01:01 UTC by roma0297

The idea behind this commit was to add `kotlin-scripting-compiler-embeddable` to the list of explicit dependencies so that is loaded during the build phase and caching is applied thus enabling us to run the `gradle run` in offline mode with `--offline` flag

2021-03-24 01:12 UTC, menewman reviewed
Yay, I'm excited to see this one too! 🙌 

Left a couple of small comments, and I have the same high-level comment that I put on the Java PR:
> I can see that the Dockerfile itself builds, but for this particular kind of change it seems really closely related to what we run on the coderunner, so I have to ask -- is there a deployed coderunner that uses this new image that shows everything is working okay?

2021-03-24 01:12 UTC, menewman commented on kotlin/build.gradle
> +    implementation "mysql:mysql-connector-java:$System.env.MYSQL_CONNECTOR_JAVA_VERSION"
Hm, it's not really anything "wrong" with this PR, but this might not work until we have a chance to release the prior change (since this env var might not be defined, if it was just added)

2021-03-24 01:12 UTC, menewman commented on kotlin/build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.5.0-M1'
Hm, I think updating the Kotlin version is great, but I'd probably feel safer sticking to the latest released version (1.4.31) rather than jumping into the preview version

2021-03-24 01:12 UTC, menewman commented on kotlin/build.gradle
>  dependencies {
If you're willing to also add `kotlinx.serialization` and `kotlinx.coroutines` it would be much appreciated!
https://kotlinlang.org/docs/serialization.html#example-json-serialization
https://github.com/Kotlin/kotlinx.coroutines/blob/master/README.md#gradle

It looks like we're manually including the coroutines plugin when compiling in the coderunner using `kotlinc`, so we'd want to adjust that to be available through the Gradle file if we change the way we run Kotlin tasks, I think.

Serialization is a new feature so I wouldn't block this PR on that; would just be nice so that we could easily do some JSON-parsing in the language template (for example, for the string input-parsing project -- see CodeSignal/coderunner#1031)

2021-03-24 05:42 UTC, DimaPhil commented on kotlin/build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.5.0-M1'
Agree with Michael, let's stick with the stable version

2021-03-24 13:35 UTC, ArDrambyan commented
Hi all :) As you already know, right now I'm bumping up the Ubuntu version for all dockerfiles and I'm afraid that my changes will result to merge conflicts. I'm sorry about that 😅

2021-03-24 23:26 UTC, roma0297 commented on kotlin/build.gradle
> +    implementation "mysql:mysql-connector-java:$System.env.MYSQL_CONNECTOR_JAVA_VERSION"
True, we decided to introduce this thing to keep the versions in sync, the order of deployments is important

2021-03-24 23:39 UTC, roma0297 commented on kotlin/build.gradle
>  dependencies {
It's just a couple of extra lines, I'm gonna add these dependencies :)

2021-03-24 23:39 UTC, roma0297 commented on kotlin/build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.5.0-M1'
I was under the impression that M1 is also stable, it's just a milestone but I can roll back a bit

2021-03-24 23:41 UTC, roma0297 commented on kotlin/build.gradle
>  dependencies {
Done 👍

2021-03-24 23:51 UTC, menewman commented on kotlin/build.gradle
>  dependencies {
Awesome 🙌

2021-03-24 23:52 UTC, menewman reviewed
Thank you for the updates! The code changes in this PR look good 👍 

I think I can't approve in good faith until after approving the Java one (since this builds on that), so I guess I'd better go give it another look first

2021-03-24 23:57 UTC, roma0297 commented
Hey @menewman, I cannot see `kotlin-gradle` tag which you created yesterday in the dockerhub, could you add it again please? I already created a PR to the coderunner repo for Kotlin but it won't work without appropriate docker image: https://github.com/CodeSignal/coderunner/pull/1115

2021-03-25 00:07 UTC, menewman commented
@roma0297 - The build rule is in place, but DockerHub currently cannot successfully build this Kotlin Dockerfile as-is because of the issue described here:
https://github.com/CodeSignal/dockerfiles/pull/340#discussion_r600077714

For example, here's the most recent failed build attempt:
https://hub.docker.com/repository/registry-1.docker.io/codesignal/kotlin/builds/260d36c9-cd2b-4aa7-8148-6e6d8b7d2e1c

If you want to try without waiting on Java, some options: we could temporarily hardcode the MySQL connector version, _or_ we could make this inherit from...
```
FROM codesignal/java:java-gradle
```

...instead of `codesignal/java:v8.1.2`.

2021-03-25 20:41 UTC, menewman requested changes
Setting status to request changes just to reflect that my status is waiting on testability

2021-12-15 12:52 UTC, closed without merging