Database Pool: Update images dependent on ubuntu-base and remove no longer used images
CodeSignal/dockerfiles pull request #388
Opened 2021-06-22 18:28 UTC by mpowaga

Summary of changes:

- Updated ubuntu-base/9.2.x to ubuntu-base/9.3.0
- Removed mysql image
- Removed mssql image

2021-06-23 07:41 UTC, salbert96 commented on elixir/Dockerfile
> +FROM codesignal/erlang:v9.3.0
For the first layer we should update only the images that are based on `codesignal/ubuntu-base`
We don't have `codesignal/erlang:v9.3.0` yet, we need to update that layer after merging this and creating a release.

2021-06-23 07:42 UTC, salbert96 commented on coffeescript/Dockerfile
> +FROM codesignal/js:v9.3.0
Same problem here.

2021-06-23 07:42 UTC, salbert96 requested changes
@mpowaga I did not write in every place, but we should only update the first layer that is based on ubuntu-base (that's the reason why the ci fails).

2021-06-23 10:26 UTC, salbert96 commented on erlang/Dockerfile
> -FROM codesignal/ubuntu-base:v9.3.0
I thinks this should be updated

2021-06-23 10:31 UTC, mpowaga commented on erlang/Dockerfile
> -FROM codesignal/ubuntu-base:v9.3.0
Good catch!

2021-06-23 11:58 UTC, salbert96 commented
@mpowaga seems like Julia does not have the last version, is it intentional?

2021-06-23 13:14 UTC, mpowaga commented
> seems like Julia does not have the last version, is it intentional?

@salbert96 It fails to build. I will update it separately to investigate why it fails.

2021-06-23 13:15 UTC, mpowaga commented
I'll create another PR that will update second layer images after new images are pushed to docker hub.

2021-06-23 13:19 UTC, salbert96 commented
> It fails to build. I will update it separately to investigate why it fails.

👍  we don't have to do it soon, feel free to create an issue and it can be done later, after the database-pool, to not block us.

2021-06-23 13:22 UTC, salbert96 approved these changes
🚢

2021-06-23 13:24 UTC, merged

2021-06-24 11:01 UTC, salbert96 commented on coffeescript/Dockerfile
> +FROM codesignal/js:v9.3.0
@mpowaga seems like this was updated from `js`. Not a big deal, but we should make sure we build everything that is based on js.